export const mockData = [
  {
    login: "saeed",
    id: 37361,
    node_id: "MDQ6VXNlcjM3MzYx",
    avatar_url: "https://avatars2.githubusercontent.com/u/37361?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/saeed",
    html_url: "https://github.com/saeed",
    followers_url: "https://api.github.com/users/saeed/followers",
    following_url: "https://api.github.com/users/saeed/following{/other_user}",
    gists_url: "https://api.github.com/users/saeed/gists{/gist_id}",
    starred_url: "https://api.github.com/users/saeed/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/saeed/subscriptions",
    organizations_url: "https://api.github.com/users/saeed/orgs",
    repos_url: "https://api.github.com/users/saeed/repos",
    events_url: "https://api.github.com/users/saeed/events{/privacy}",
    received_events_url: "https://api.github.com/users/saeed/received_events",
    type: "User",
    site_admin: false,
    score: 1.0,
  },
  {
    login: "saeedsh92",
    id: 9940633,
    node_id: "MDQ6VXNlcjk5NDA2MzM=",
    avatar_url: "https://avatars0.githubusercontent.com/u/9940633?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/saeedsh92",
    html_url: "https://github.com/saeedsh92",
    followers_url: "https://api.github.com/users/saeedsh92/followers",
    following_url:
      "https://api.github.com/users/saeedsh92/following{/other_user}",
    gists_url: "https://api.github.com/users/saeedsh92/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/saeedsh92/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/saeedsh92/subscriptions",
    organizations_url: "https://api.github.com/users/saeedsh92/orgs",
    repos_url: "https://api.github.com/users/saeedsh92/repos",
    events_url: "https://api.github.com/users/saeedsh92/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/saeedsh92/received_events",
    type: "User",
    site_admin: false,
    score: 1.0,
  },
];
